dist: trusty
language: java
sudo: required
jdk:
- oraclejdk8
before_script:
- wget "https://github.com/nats-io/nats-streaming-server/releases/download/$stan_version/nats-streaming-server-$stan_version-linux-amd64.zip"
  -O tmp.zip
- unzip tmp.zip
- mv nats-streaming-server-$stan_version-linux-amd64 stan
before_install:
- openssl aes-256-cbc -K $encrypted_4d67c1484586_key -iv $encrypted_4d67c1484586_iv -in nats.travis.gpg.enc -out .travis/nats.travis.gpg -d
install:
- "./gradlew assemble -x signArchives"
script:
- "./gradlew check"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- "./gradlew test jacocoTestReport coveralls"
env:
  global:
  - stan_version=v0.10.2
  - stan_path=$TRAVIS_BUILD_DIR/stan/nats-streaming-server
  - GPG_KEYRING_FILE=.travis/nats.travis.gpg
  - secure: eQyGeyljLMlv3QFIVxViQ9HmT9/Dw7F8swSRa8Do5c+YlFaTqOshKl4HbPewOLVFV5KslUJh0Flp2+QrWG6KIo/2Fb7HeRZRXrBTuCCSuHNFEkEnSRGtEeWwr8vITtgILnelEioWPNiV6dAzIDrVf55FcPc5VQAi5tx8fMlql4+UxTVZVta5TyQ/zJRiABGygyXUx5WA+4AJEVtmXQPDVBCHf0BgKsvp0DkYiqMzzoKSi1Lgl8bm0UBvJF/wLMA6rPSAl05WTeZN9w3Palxla7DFA9T0XF97pfQSdAwLuKIOvLs92gwa8jYSDw6qA+08XxnAuC/pZd/p0+JIfxgzSlxm437KP8AJG3IrcPhOkO9QKf11MAro+CSTMjA5pTSwDD3r+BzijtdDbniXtMS+pUUrsTvMyNeKb8mvvUvBtLMMykJz7O4DbqBvs7f5PFt4NxkbmrDmzWGyptmzQtPx0qLkqs4MfPOF9PDxtSGrUmj2qSoh8OhKdDBaEmVxUdhQ7/yj4W2YrBCXToxM0gXzdjjYSL58YFoZ3MVqBYuOogFJOh/0KxrJ9jaUkWLADOEjZndF6mkWMU1Z7DyBu3X2srP6qT2bnwBDt8cheo8epVNbEC0vf0BSCY7KApl7oJFjmheQYw2vIFhVQ2y6VZEvENkPu+RdzF+0wjb+WlVzKFc=
  - secure: nFXz8ikanipC3EPiIn2Qcwhp/WDGU3/Ohimq2J8iLjGXIq1SXWwCgDeD3yg6ad2DE7RygnvAO59g3HorIAicEVWiW8kmi5thHU/ET/4oL9IRl55NPjEvrk/1JxCWCQ38FomedVrpf9Tgj+zVFTqmZImEAXwTqtmNh54Kx7+Ze7/rpptFGNSmVmpCJ1WKQPFbHympbsAZGRSHIr6gchhqa3pXRMtmBf7KhycvFm8A3RChP8kvZKA4Tqixd1JJyRsy5VOCo8LQ4ESV/14pk8lReV/c6EJTOH07ytbiOLDxq+Tl4H4FecyfQg/GZ6WI3uQIRKJ7CZmSIH/VtmHhgqZIZdZjN4eTQBAmFghf/Z0/t4b26aefqddDItW4LXMEU5btlbTgqdNbbJp4GSVbYC2x7xcW2u4YdYsKLqYbfKMHHgwWOyEba+6oyE9JGKOmQBjNc7se2JdEoSkMzmbr+YcZlMDeec4kURA6eCxsKUXh/JLWemHZcZX5O3mNh88TzJEwBFvpRlVm9DfuMUZFcU2RQSnDFOYgr/JSZ+QXWrRDwi6cvvutzECRu5zmco6dHHCKdlmoihtcEHrq032o4kz8+tge13utKMVQ+mTzFpsMeO7pLTvT+juO7qx5iAcnLb6qj940XtsbfeBvHlFWxF2tSXM/YFBI2vJtb963Of0HAE8=
  - secure: ux5q9GEzUchYdw7qM31LfCFtkU0cdKGBzkAcrCyZiNUzDhUlQK5DeyDG7assiPkVtMdKITXi75mF3DY+2pukNU0M/NaOeJ+i3AP8sKjEV71NCVtYHNerwwoA5tYHnZxp6EfoWT5pceXzcQvx/6XcwezQa9KligBbVCvANUMgqC9x9rlaZvwRECARjpeQdsvGVMKe2Su/uackhVpJ50m/4urHUbMQugXBLmBIbp/2r9AdKi/rwVn01ekIbBLgzLi8daYn7xuXlyQLHCIuqCyqQZpodrYMF6Z3tiGO6EheqspynnKsklsS6YHion5BZ9RRv1kQH2pgXKz26FWsdm7096kOveo3vdzwQdB41oSvk+3Kcut0Wq99aM85jqOw9aP242JhHsk6HBvuECODGEf0VePZhQGoGS3srNAxnDDCchId1ZVMHqsnW37QnxcWQEN0PMr3mb3Bmnu+WUA+a1kusJuTsmmzTi/sahxFeBMCR+4+LXzatOjFtAeVFHsq3g0GRif80JpcTIHswlcRPCXt2eLg4GRNV36u3FHMG5hyWstS5cTKRopYij5edwFQsm4InkgLVgvjlfVIzi2jUc6TaIqibtVU0/tXdLaOsp1YZ90IVluyzbCi7s1k31bXULhkQ1gWn5TZ70/2N0uV2ERLMzR6Tg7Z2dPlUyGqRiCO/to=
  - secure: FEWIxFjGm3YkPSHiYytuWd473MQik7rOo6yGTk3drihTUXTojnbtNufTaOKI7X8Gj2hmb0zYnf3pvrDlrEGXq8TXdDXOy5j2VACEKKRuhAzCWJEbEMnua6DRuSqTfW2Zdf9idJjNQXO/wCJJ5xOh2cngcjjWNLWG8qj7dLBRPXJnAZ/U37CoUCgQfNZe9hbxjGEsoGUleDMNWLncADaqbYd8G3CO32oYj5ay0CpLaysWT/kLXh//kicSPHaI9Ozz59MTsCxxaO56YzxNrE4bIKtKo0UolnHVHEh+Vsz3AdrC9pOEwSk7gMzCACFsSCP44jMqYUbx58gGlQJ78HLflnIK+/qz2TcfC8/5WtWrNGjvWFiF/4RrfLDWBmx0dPBCI2kRcHmGmH51cbBk8s+/MBifnkICk69ywD+bWD5brbjJi/wXkVuUvf3XxpzeaGqfWEKXy6JmJnwMBY9oG20gZRGU/Vw6NSusM+1mgvbyVgqq3t+jEHCPV+wfPmOjvdz9iFYfop/eCQCdm2WGxWDl9DgH8+K7XiwKTDmUXZStfykEyNOSC8fjMZHXyYdsSDBykFKve/fZlkhHIjHSrkTlt8mVD9zH5dIZ1xkO1XN+F/MGvHbkwCU1S7V9kqyM0hSRCcaqiv8N+VqNoBovK/4C7tLD2TdZs9L1a3IF0KCDY6k=
